# Generated by Django 5.0.1 on 2024-02-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "treatments",
            "0005_prescription_medicine_diagnosis_advice_symptom_test_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="notes",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
