# Generated by Django 5.0.1 on 2024-02-11 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatments", "0006_alter_prescription_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advice",
            name="prescription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advices",
                to="treatments.prescription",
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="prescription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagnoses",
                to="treatments.prescription",
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="prescription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medicines",
                to="treatments.prescription",
            ),
        ),
        migrations.AlterField(
            model_name="symptom",
            name="prescription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="symptoms",
                to="treatments.prescription",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="prescription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="treatments.prescription",
            ),
        ),
    ]
