# Generated by Django 5.0.1 on 2024-02-11 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("treatments", "0008_prescriptionaccess_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PrescriptionAccess",
        ),
    ]
