# Generated by Django 5.0.1 on 2024-02-11 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0006_degree_unique_doctor_degree_speciality"),
        ("patients", "0004_alter_speciality_unique_together_and_more"),
        ("treatments", "0009_delete_prescriptionaccess"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrescriptionAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doctors.doctor"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="treatments.prescription",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="prescriptionaccess",
            constraint=models.UniqueConstraint(
                fields=("prescription", "doctor"), name="unique_prescription_doctor"
            ),
        ),
    ]
