# Generated by Django 5.0.1 on 2024-02-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0005_degree_speciality"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="degree",
            constraint=models.UniqueConstraint(
                fields=("username", "degree", "speciality"),
                name="unique_doctor_degree_speciality",
            ),
        ),
    ]
